name: jaffle_shop_3

profile: jaffle_shop_3

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  jaffle_shop_3:
    +schema: raw

models:
  jaffle_shop_3:
    # Materialize staging models as views, and marts as tables
    bronze:
      +materialized: table
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
    ephemeral:
      +materialized: ephemeral
    